# Change these first
owner: blazels # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:
  - name: BlazeLS
    url: https://blazels.xyz
  - name: CDN
    url: https://cdn-user.blazels.xyz
  - name: Patch
    url: https://cdn-up.blazels.xyz
  - name: Storage
    url: https://s3.jagoanstorage.com/download/index.html
  - name: SQLServ
    check: "tcp-ping"
    url: azure.blazels.xyz
    port: 1433
  - name: Gamesvr
    check: "tcp-ping"
    url: server.blazels.xyz
    port: 14009

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.blazels.xyz
  # baseUrl: /stats
  favicon: https://blazels.xyz/assets/img/favicon/apple-touch-icon.png
  logoUrl: https://blazels.xyz/logo.png
  name: .
  introTitle: "**Blazestat** for status Server Blaze."
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  navbar:
    - title: BlazeLS
      href: https://blazels.xyz
    - title: Discord
      href: https://discord.gg/T7KcEWqvvN
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
